name: userorient_flutter
description: "Discover what your users really want and stop building wrong features."
version: 0.1.1
homepage: https://userorient.com
repository: https://github.com/userorient/userorient-flutter
issue_tracker: https://github.com/userorient/userorient-flutter/issues
topics:
  - feature-request
  - feedback
  - user-experience
  - board
  - upvote

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  http: ^1.2.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: